name: company_roster
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: 7.2.0
  dio: ^5.3.2
  bloc: ^8.1.2
  injectable: ^2.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  data_connection_checker_nulls: ^0.0.2
  auto_route: 7.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
